# Generated by Django 3.0 on 2022-10-07 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EventName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('guest', models.CharField(blank=True, max_length=200, null=True)),
                ('convenor', models.CharField(blank=True, max_length=200, null=True)),
                ('banner', models.ImageField(upload_to='banners/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.Department')),
                ('eventtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.EventName')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.Venue')),
            ],
        ),
    ]
