# Generated by Django 3.0 on 2022-10-07 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mode',
            field=models.CharField(blank=True, choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(help_text='Eg time: 18:00:00 means 6 pm'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(help_text='Eg time: 06:00:00 means 6 am'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Events.Venue'),
        ),
    ]
