# Generated by Django 3.0 on 2022-10-07 20:23

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_auto_20221007_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('on going', 'on going')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[1000, 400], upload_to='banners/'),
        ),
    ]
