# Generated by Django 3.0 on 2022-10-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_remove_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='meet_url',
            field=models.URLField(blank=True, default=None, help_text='T3z3wx', max_length=2083, null=True),
        ),
    ]
